### ISSUE TITLE
Excwption

### ISSUE THREAD

**Issue by michael-spasov** [eltonsandre/intellij-spring-boot-helper#10]
Unhandled PCE in [CoroutineName(dev.eltonsandre.intellij.spring.src.Cmp.OoOO), StandaloneCoroutine{Cancelling}@2df4885d, Dispatchers.Default]. Try wrapping the throwing code into `blockingContext {}`
   
   java.lang.IllegalStateException: com.intellij.ide.startup.ServiceNotReadyException: index Stubs has status DOING_REBUILD
	at com.intellij.openapi.application.impl.CoroutineExceptionHandlerImpl.handleException(CoroutineExceptionHandlerImpl.kt:26)
	at kotlinx.coroutines.internal.CoroutineExceptionHandlerImpl_commonKt.handleUncaughtCoroutineException(CoroutineExceptionHandlerImpl.common.kt:38)
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:32)
	at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:194)
	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:230)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:909)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:866)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:831)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
	at kotlinx.coroutines.debug.internal.DebugProbesImpl$CoroutineOwner.resumeWith(DebugProbesImpl.kt:538)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: com.intellij.ide.startup.ServiceNotReadyException: index Stubs has status DOING_REBUILD
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:821)
	at com.intellij.psi.stubs.StubIndexEx.getContainingIds(StubIndexEx.java:369)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:170)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:102)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:90)
	at com.intellij.psi.impl.java.stubs.index.JavaFullClassNameIndex.get(JavaFullClassNameIndex.java:34)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.doFindClasses(JavaFileManagerImpl.java:81)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.findClass(JavaFileManagerImpl.java:104)
	at com.intellij.psi.impl.PsiElementFinderImpl.findClass(PsiElementFinderImpl.java:40)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.doFindClass(JavaPsiFacadeImpl.java:94)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:72)
	at dev.eltonsandre.intellij.spring.cmmn.Ul.G.super(
IIII
I
II
II
lI
I
lI
lIlIl
l)
	at dev.eltonsandre.intellij.spring.cmmn.Ul.G.super(
IIII
I
II
II
lI
I
lI
lIlIl
l)
	at dev.eltonsandre.intellij.spring.cmmn.Ul.private.Ò00000(
lIll
l
I
IlI
I
l
l
I
l
II
l
l
I
l)
	at com.intellij.util.containers.ConcurrentFactoryMap$2.create(ConcurrentFactoryMap.java:174)
	at com.intellij.util.containers.ConcurrentFactoryMap.get(ConcurrentFactoryMap.java:40)
	at java.base/java.util.concurrent.ConcurrentMap.getOrDefault(ConcurrentMap.java:88)
	at dev.eltonsandre.intellij.spring.cmmn.Ul.private.o00000(
lIll
l
I
IlI
I
l
l
I
l
II
l
l
I
l)
	at dev.eltonsandre.intellij.spring.cmmn.Ul.private.Ô00000(
lIll
l
I
IlI
I
l
l
I
l
II
l
l
I
l)
	at dev.eltonsandre.intellij.spring.src.Cmp.OoOO.Object(IIIIlllI
ll
I
lI
II
lIII
l)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode$lambda$2(DumbService.kt:117)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:923)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:76)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.kt:110)
	at dev.eltonsandre.intellij.spring.src.Cmp.OoOO.runActivity(IIIIlllI
ll
I
lI
II
lIII
l)
	at dev.eltonsandre.intellij.spring.src.Cmp.OoOO.execute(IIIIlllI
ll
I
lI
II
lIII
l)
	at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1$1.invokeSuspend(StartupManagerImpl.kt:534)
	at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1$1.invoke(StartupManagerImpl.kt)
	at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1$1.invoke(StartupManagerImpl.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1.invokeSuspend(StartupManagerImpl.kt:532)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	... 5 more
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(dev.eltonsandre.intellij.spring.src.Cmp.OoOO), StandaloneCoroutine{Cancelled}@2df4885d, Dispatchers.Default]

**Comment by eltonsandre** [comment]
Hi @michael-spasov ,
Fixed in version [2023.1.0](https://plugins.jetbrains.com/plugin/18622-spring-boot-helper/versions/stable/472683)
