### ISSUE TITLE
Plugin throws exception when intellij ide starts up

### ISSUE THREAD

**Issue by myunghoonju** [eltonsandre/intellij-spring-boot-helper#15]
**Describe the bug**
IDE internal error popup shows.

**To Reproduce**
1. run ide.
2. popup shows an error.

**Expected behavior**
error popup not showing

**Screenshots**
![Screenshot 2024-10-22 at 21 53 55](https://github.com/user-attachments/assets/1b35896c-2fc8-4080-8795-c64d2d8bfa38)

---
**Version information** 
IntelliJ IDEA 2024.2.3 (Ultimate Edition)
Build #IU-242.23339.11, built on September 25, 2024
Runtime version: 21.0.4+13-b509.17 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.6.1
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  com.github.nizienko.SpaceInvaders (1.1.0)
  com.github.izhangzhihao.intellijgooglesearch (0.0.2)
  com.jetbrains.darkPurpleTheme (1.3)
  com.kagof.pokeprogress (2.1.1)
  dev.eltonsandre.intellij.spring.assistant.plugin (2023.1.3)
  uk.co.ben-gibson.remote.repository.mapper (4.5.2)
Kotlin: 242.23339.11-IJ

<details>
<summary>Version Details</summary>

```
// past version details here
```

</details>

---
**Exception**

<details>
<summary>Stack trace</summary>

```java

//Past Stack trace here
com.intellij.diagnostic.PluginException: null [Plugin: dev.eltonsandre.intellij.spring.assistant.plugin]
	at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1.invokeSuspend(StartupManagerImpl.kt:502)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at dev.eltonsandre.spring.Bcct.sggt.MtDt.ooOO.Ò00000(ll
I
l
ll
l
```
</details>

---

**Additional context**

**Comment by eltonsandre** [comment]
Hi @myunghoonju,
Thanks for reporting, I'll look into it and work on fixing it.

**Comment by eltonsandre** [comment]
Hi @myunghoonju,

I hope the new version has fixed the issue. I look forward to your feedback.
TNX!

**Comment by myunghoonju** [comment]
Hi it worked and the error's gone.
Thank you.
