### ISSUE TITLE
exception in intelliji idea 2022.2

### ISSUE THREAD

**Issue by clayly** [eltonsandre/intellij-spring-boot-helper#3]
Once happened on start, can't catch it again.

Intelliji IDEA:

```text
IntelliJ IDEA 2022.2 (Ultimate Edition)
Build #IU-222.3345.118, built on July 26, 2022
Licensed to Circuit Engineering Technologies, LLC / Vladimir Zinchuk
You have a perpetual fallback license for this version.
Subscription is active until January 19, 2023.
Runtime version: 17.0.3+7-b469.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 6
Registry:
    scala.erase.compiler.process.jdk.once=false

Non-Bundled Plugins:
    org.rust.lang (0.4.175.4772-222)
    org.jetbrains.plugins.go-template (222.3345.108)
    name.kropp.intellij.makefile (222.3345.108)
    detekt (1.21.0)
    com.jetbrains.plugins.ini4idea (222.3345.144)
    com.jetbrains.edu (2022.7-2022.2-291)
    com.intellij.plugins.watcher (222.3345.111)
    com.intellij.nativeDebug (222.3345.111)
    com.intellij.javafx (1.0.4)
    com.intellij.ideolog (203.0.30.0)
    org.jetbrains.plugins.hocon (2022.1.0)
    jd-intellij (0.8.1)
    com.tang (1.3.7.2-IDEA222)
    YAML/Ansible support (0.11.2)
    org.jetbrains.plugins.go (222.3345.118)
    String Manipulation (9.5.1)
    Statistic (4.1.10)
    Key Promoter X (2022.2)
    GrepConsole (12.14.211.6693.0)
    org.sonarlint.idea (7.0.0.52289)
    mobi.hsz.idea.gitignore (4.4.2)
    PlantUML integration (5.16.1)
    org.asciidoctor.intellij.asciidoc (0.37.36)
    com.crunch42.openapi (1.34)
    com.atlassian.bitbucket.references (2020.3.206)
    com.intellij.kubernetes (222.3345.108)
    CheckStyle-IDEA (5.70.0)
    CMD Support (1.0.5)
    Dart (222.3345.108)
    io.flutter (69.0.5)
    com.dmarcotte.handlebars (222.3345.108)
    Pythonid (222.3345.131)
    ru.adelf.idea.dotenv (2022.2)
    org.jetbrains.kotlin-js-inspection-pack-plugin (0.0.10)
    dev.eltonsandre.intellij.spring.assistant.plugin (2022.2.2)
    com.haulmont.jpab (2022.3.4-222)
    aws.toolkit (1.49-222)
    MavenRunHelper (4.21.222.2964.0)
    zielu.gittoolbox (212.9.7)
    org.intellij.scala (2022.2.12)
    com.intellij.bigdatatools (222.3345.33)
    izhangzhihao.rainbow.brackets (6.25)
    cn.yiiguxing.plugin.translate (3.3.4)

Kotlin: 222-1.7.10-release-334-IJ3345.118
```

Exception:

```text
Unhandled exception in [CoroutineName(DocumentationBrowser requests), StandaloneCoroutine{Cancelling}@56dcf380, Dispatchers.Default]

java.lang.IllegalAccessError: Method should never be called for a generic class
	at dev.eltonsandre.intellij.spring.suggestion.A.D.A(Unknown Source)
	at dev.eltonsandre.intellij.spring.suggestion.A.H.B(Unknown Source)
	at dev.eltonsandre.intellij.spring.suggestion.A.J.A(Unknown Source)
	at dev.eltonsandre.intellij.spring.suggestion.A.J.A(Unknown Source)
	at dev.eltonsandre.intellij.spring.suggestion.A.J.A(Unknown Source)
	at dev.eltonsandre.intellij.spring.suggestion.metadata.json.F.A(Unknown Source)
	at dev.eltonsandre.intellij.spring.suggestion.metadata.json.F.A(Unknown Source)
	at dev.eltonsandre.intellij.spring.suggestion.metadata.json.F.A(Unknown Source)
	at dev.eltonsandre.intellij.spring.suggestion.metadata.json.F.A(Unknown Source)
	at dev.eltonsandre.intellij.spring.suggestion.metadata.C.A(Unknown Source)
	at dev.eltonsandre.intellij.spring.boot.application.yaml.ApplicationYamlDocumentationProvider.generateDoc(Unknown Source)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.generateDoc(CompositeDocumentationProvider.java:135)
	at com.intellij.lang.documentation.psi.PsiElementDocumentationTarget.localDocHtml(PsiElementDocumentationTarget.kt:102)
	at com.intellij.lang.documentation.psi.PsiElementDocumentationTarget.localDoc(PsiElementDocumentationTarget.kt:88)
	at com.intellij.lang.documentation.psi.PsiElementDocumentationTarget.computeDocumentation(PsiElementDocumentationTarget.kt:75)
	at com.intellij.lang.documentation.impl.ImplKt$computeDocumentation$2$documentationResult$1.invoke(impl.kt:31)
	at com.intellij.lang.documentation.impl.ImplKt$computeDocumentation$2$documentationResult$1.invoke(impl.kt)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:96)
	at com.intellij.openapi.application.rw.InternalReadAction.access$insideReadAction(InternalReadAction.kt:13)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$1.invoke(InternalReadAction.kt:81)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$1.invoke(InternalReadAction.kt:13)
	at com.intellij.openapi.progress.CancellationKt$sam$com_intellij_openapi_util_ThrowableComputable$0.compute(cancellation.kt)
	at com.intellij.openapi.progress.Cancellation.withJob(Cancellation.java:60)
	at com.intellij.openapi.progress.CancellationKt.withJob(cancellation.kt:14)
	at com.intellij.openapi.progress.CancellationKt.executeWithJobAndCompleteIt(cancellation.kt:111)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$2$1.run(cancellableReadAction.kt:33)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$2.run(cancellableReadAction.kt:31)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:158)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:29)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:80)
	at com.intellij.openapi.application.rw.InternalReadAction.access$tryReadCancellable(InternalReadAction.kt:13)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadAction$2.invoke(InternalReadAction.kt:66)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadAction$2.invoke(InternalReadAction.kt:13)
	at com.intellij.openapi.progress.CancellationKt$sam$com_intellij_openapi_util_ThrowableComputable$0.compute(cancellation.kt)
	at com.intellij.openapi.progress.Cancellation.withJob(Cancellation.java:60)
	at com.intellij.openapi.progress.CancellationKt.withJob(cancellation.kt:14)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:138)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:61)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:53)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:13)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invokeSuspend(InternalReadAction.kt:33)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at com.intellij.openapi.application.rw.InternalReadAction.runReadAction(InternalReadAction.kt:32)
	at com.intellij.openapi.application.rw.PlatformReadActionSupport.executeReadAction(PlatformReadActionSupport.kt:24)
	at com.intellij.openapi.application.CoroutinesKt.constrainedReadAction(coroutines.kt:47)
	at com.intellij.openapi.application.CoroutinesKt.readAction(coroutines.kt:17)
	at com.intellij.lang.documentation.impl.ImplKt$computeDocumentation$2.invokeSuspend(impl.kt:30)
	at com.intellij.lang.documentation.impl.ImplKt$computeDocumentation$2.invoke(impl.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.lang.documentation.impl.ImplKt.computeDocumentation(impl.kt:29)
	at com.intellij.lang.documentation.ide.impl.DocumentationPage.loadPage(DocumentationPage.kt:32)
	at com.intellij.lang.documentation.ide.impl.DocumentationBrowser.handleBrowserRequest(DocumentationBrowser.kt:91)
	at com.intellij.lang.documentation.ide.impl.DocumentationBrowser.access$handleBrowserRequest(DocumentationBrowser.kt:24)
	at com.intellij.lang.documentation.ide.impl.DocumentationBrowser$1$1.invokeSuspend(DocumentationBrowser.kt:51)
	at com.intellij.lang.documentation.ide.impl.DocumentationBrowser$1$1.invoke(DocumentationBrowser.kt)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invokeSuspend(Merge.kt:217)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Merge.kt)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Merge.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(Merge.kt:34)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Merge.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Merge.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$invokeSuspend$$inlined$collect$1.emit(Collect.kt:140)
	at kotlinx.coroutines.flow.SharedFlowImpl.collect(SharedFlow.kt:351)
	at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(SharedFlow.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by eltonsandre** [comment]
Could not reproduce the error, perhaps a one-time incident. we will reopen the problem if it persists
