### ISSUE TITLE
Error parsing configuration yml file

### ISSUE THREAD

**Issue by michael-spasov** [eltonsandre/intellij-spring-boot-helper#9]
Error during processing of: application-dev.yml
   
   com.intellij.psi.PsiInvalidElementAccessException: Element class com.intellij.psi.impl.source.tree.java.ClassElement of type CLASS (class com.intellij.psi.impl.java.stubs.JavaStubElementTypes$1)
	at com.intellij.psi.PsiInvalidElementAccessException.createByNode(PsiInvalidElementAccessException.java:80)
	at com.intellij.psi.impl.source.SubstrateRef$2.getContainingFile(SubstrateRef.java:74)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getContainingFile(StubBasedPsiElementBase.java:235)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getProject(StubBasedPsiElementBase.java:271)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at dev.eltonsandre.intellij.spring.cmmn.Ul.G.super(
IIII
I
II
II
lI
I
lI
lIlIl
l)
	at dev.eltonsandre.intellij.spring.sggt.Clz.SaoPaulo.Õ00000(
lI
IlI
l
lIlI
I
l
I
I
I
lIl
ll)
	at dev.eltonsandre.intellij.spring.sggt.Clz.SaoPaulo.o00000(
lI
IlI
l
lIlI
I
l
I
I
I
lIl
ll)
	at dev.eltonsandre.intellij.spring.sggt.Clz.SaoPaulo.o00000(
lI
IlI
l
lIlI
I
l
I
I
I
lIl
ll)
	at dev.eltonsandre.intellij.spring.isb.apptn.Object.o00000(
Illl
II
I
I
l
l
lIlIlI
ll
ll)
	at dev.eltonsandre.intellij.spring.isb.apptn.Object.o00000(
Illl
II
I
I
l
l
lIlIlI
ll
ll)
	at dev.eltonsandre.intellij.spring.isb.apptn.Object.o00000(
Illl
II
I
I
l
l
lIlIlI
ll
ll)
	at dev.eltonsandre.intellij.spring.isb.apptn.Yl.super.resolve(I
ll
llI
IlI
lll
l
IIl
l
lI
I)
	at com.intellij.psi.PsiReferenceBase.isReferenceTo(PsiReferenceBase.java:118)
	at com.intellij.psi.search.SingleTargetRequestResultProcessor.processTextOccurrence(SingleTargetRequestResultProcessor.java:35)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$5.lambda$execute$0(PsiSearchHelperImpl.java:968)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processTreeUp(LowLevelSearchUtil.java:85)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.lambda$processElementsAtOffsets$0(LowLevelSearchUtil.java:176)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processOffsets(LowLevelSearchUtil.java:203)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsAtOffsets(LowLevelSearchUtil.java:175)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$5.execute(PsiSearchHelperImpl.java:964)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:289)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:280)
	at com.intellij.openapi.application.ReadActionProcessor.lambda$process$0(ReadActionProcessor.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:923)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:76)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:11)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processCandidates$18(PsiSearchHelperImpl.java:925)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processVirtualFile$11(PsiSearchHelperImpl.java:561)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processVirtualFile(PsiSearchHelperImpl.java:540)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processPsiFileRoots$7(PsiSearchHelperImpl.java:411)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processFilesConcurrentlyDespiteWriteActions$9(PsiSearchHelperImpl.java:482)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:207)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processFilesConcurrentlyDespiteWriteActions$10(PsiSearchHelperImpl.java:481)
	at com.intellij.concurrency.JobLauncherImpl.lambda$processImmediatelyIfTooFew$2(JobLauncherImpl.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.concurrency.JobLauncherImpl.lambda$processImmediatelyIfTooFew$3(JobLauncherImpl.java:140)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:895)
	at com.intellij.concurrency.JobLauncherImpl.processImmediatelyIfTooFew(JobLauncherImpl.java:151)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:47)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:51)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processFilesConcurrentlyDespiteWriteActions(PsiSearchHelperImpl.java:498)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processPsiFileRoots$8(PsiSearchHelperImpl.java:408)
	at com.intellij.psi.impl.PsiManagerImpl.runInBatchFilesMode(PsiManagerImpl.java:455)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processPsiFileRoots(PsiSearchHelperImpl.java:401)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processCandidates(PsiSearchHelperImpl.java:920)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processGlobalRequests(PsiSearchHelperImpl.java:890)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processGlobalRequestsOptimized(PsiSearchHelperImpl.java:856)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processRequests(PsiSearchHelperImpl.java:781)
	at com.intellij.psi.search.SearchRequestQuery.processResults(SearchRequestQuery.java:21)
	at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:88)
	at com.intellij.util.AbstractQuery.delegateProcessResults(AbstractQuery.java:105)
	at com.intellij.util.MergeQuery.processResults(MergeQuery.java:22)
	at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:88)
	at com.intellij.util.AbstractQuery.delegateProcessResults(AbstractQuery.java:105)
	at com.intellij.util.UniqueResultsQuery.processResults(UniqueResultsQuery.java:37)
	at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:88)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:80)
	at com.intellij.util.AbstractQuery.findFirst(AbstractQuery.java:44)
	at com.intellij.spring.boot.application.config.SpringBootConfigFileHighlightingUtil.highlightUnresolvedConfigKey(SpringBootConfigFileHighlightingUtil.java:75)
	at com.intellij.spring.boot.application.yaml.SpringBootApplicationYamlInspection$1.visitElement(SpringBootApplicationYamlInspection.java:138)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:270)
	at org.jetbrains.yaml.psi.impl.YAMLKeyValueImpl.accept(YAMLKeyValueImpl.java:225)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:59)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:41)
	at com.intellij.spring.boot.application.yaml.SpringBootApplicationYamlInspection$1.visitElement(SpringBootApplicationYamlInspection.java:85)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:270)
	at org.jetbrains.yaml.psi.impl.YAMLValueImpl.accept(YAMLValueImpl.java:40)
	at org.jetbrains.yaml.psi.impl.YAMLCompoundValueImpl.accept(YAMLCompoundValueImpl.java:45)
	at org.jetbrains.yaml.psi.impl.YAMLMappingImpl.accept(YAMLMappingImpl.java:78)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:59)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:41)
	at com.intellij.spring.boot.application.yaml.SpringBootApplicationYamlInspection$1.visitElement(SpringBootApplicationYamlInspection.java:85)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:270)
	at org.jetbrains.yaml.psi.impl.YAMLKeyValueImpl.accept(YAMLKeyValueImpl.java:225)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:59)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:41)
	at com.intellij.spring.boot.application.yaml.SpringBootApplicationYamlInspection$1.visitElement(SpringBootApplicationYamlInspection.java:85)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:270)
	at org.jetbrains.yaml.psi.impl.YAMLValueImpl.accept(YAMLValueImpl.java:40)
	at org.jetbrains.yaml.psi.impl.YAMLCompoundValueImpl.accept(YAMLCompoundValueImpl.java:45)
	at org.jetbrains.yaml.psi.impl.YAMLMappingImpl.accept(YAMLMappingImpl.java:78)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:59)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:41)
	at com.intellij.spring.boot.application.yaml.SpringBootApplicationYamlInspection$1.visitElement(SpringBootApplicationYamlInspection.java:85)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:270)
	at org.jetbrains.yaml.psi.impl.YAMLKeyValueImpl.accept(YAMLKeyValueImpl.java:225)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:59)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:41)
	at com.intellij.spring.boot.application.yaml.SpringBootApplicationYamlInspection$1.visitElement(SpringBootApplicationYamlInspection.java:85)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:270)
	at org.jetbrains.yaml.psi.impl.YAMLValueImpl.accept(YAMLValueImpl.java:40)
	at org.jetbrains.yaml.psi.impl.YAMLCompoundValueImpl.accept(YAMLCompoundValueImpl.java:45)
	at org.jetbrains.yaml.psi.impl.YAMLMappingImpl.accept(YAMLMappingImpl.java:78)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:59)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:41)
	at com.intellij.spring.boot.application.yaml.SpringBootApplicationYamlInspection$1.visitElement(SpringBootApplicationYamlInspection.java:85)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:270)
	at org.jetbrains.yaml.psi.impl.YAMLKeyValueImpl.accept(YAMLKeyValueImpl.java:225)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:59)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:41)
	at com.intellij.spring.boot.application.yaml.SpringBootApplicationYamlInspection$1.visitElement(SpringBootApplicationYamlInspection.java:85)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:270)
	at org.jetbrains.yaml.psi.impl.YAMLValueImpl.accept(YAMLValueImpl.java:40)
	at org.jetbrains.yaml.psi.impl.YAMLCompoundValueImpl.accept(YAMLCompoundValueImpl.java:45)
	at org.jetbrains.yaml.psi.impl.YAMLMappingImpl.accept(YAMLMappingImpl.java:78)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:59)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:41)
	at com.intellij.spring.boot.application.yaml.SpringBootApplicationYamlInspection$1.visitElement(SpringBootApplicationYamlInspection.java:85)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:270)
	at org.jetbrains.yaml.psi.impl.YAMLKeyValueImpl.accept(YAMLKeyValueImpl.java:225)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:59)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:41)
	at com.intellij.spring.boot.application.yaml.SpringBootApplicationYamlInspection$1.visitElement(SpringBootApplicationYamlInspection.java:85)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:270)
	at org.jetbrains.yaml.psi.impl.YAMLValueImpl.accept(YAMLValueImpl.java:40)
	at org.jetbrains.yaml.psi.impl.YAMLCompoundValueImpl.accept(YAMLCompoundValueImpl.java:45)
	at org.jetbrains.yaml.psi.impl.YAMLMappingImpl.accept(YAMLMappingImpl.java:78)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:59)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:41)
	at com.intellij.spring.boot.application.yaml.SpringBootApplicationYamlInspection$1.visitElement(SpringBootApplicationYamlInspection.java:85)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:270)
	at org.jetbrains.yaml.psi.impl.YAMLKeyValueImpl.accept(YAMLKeyValueImpl.java:225)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:59)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:41)
	at com.intellij.spring.boot.application.yaml.SpringBootApplicationYamlInspection$1.visitElement(SpringBootApplicationYamlInspection.java:85)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:270)
	at org.jetbrains.yaml.psi.impl.YAMLValueImpl.accept(YAMLValueImpl.java:40)
	at org.jetbrains.yaml.psi.impl.YAMLCompoundValueImpl.accept(YAMLCompoundValueImpl.java:45)
	at org.jetbrains.yaml.psi.impl.YAMLMappingImpl.accept(YAMLMappingImpl.java:78)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:59)
	at com.intellij.spring.boot.application.yaml.SpringBootApplicationYamlInspection.checkFile(SpringBootApplicationYamlInspection.java:81)
	at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:138)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:59)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$10(InspectionRunner.java:322)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$11(InspectionRunner.java:342)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:207)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$12(InspectionRunner.java:348)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:159)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:151)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$13(InspectionRunner.java:311)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$14(InspectionRunner.java:311)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.lambda$call$0(JobLauncherImpl.java:314)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.call(JobLauncherImpl.java:299)
	at com.intellij.concurrency.JobLauncherImpl.processQueue(JobLauncherImpl.java:367)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.processInOrder(InspectionRunner.java:310)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.visitElements(InspectionRunner.java:285)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$inspect$4(InspectionRunner.java:129)
	at com.intellij.codeInspection.InspectionEngine.withSession(InspectionEngine.java:227)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.inspect(InspectionRunner.java:115)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:113)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:95)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:390)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:77)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:24)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:386)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:377)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:376)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:352)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:207)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:350)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:190)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by eltonsandre** [comment]
Hi @michael-spasov 

Thanks for reporting!

Could you give me an example of your application-dev.yml?
